### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by leonkacowicz** [juliuszint/asdbctl#2]
When following build instructions I get this error msg:

```
error: failed to download `bit-set v0.2.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/***/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bit-set-0.2.0/Cargo.toml`

Caused by:
  dependency (bit-vec) specified without providing a local path, Git repository, version, or workspace dependency to use

```

I tried playing with the versions to see if any different version would work, but none did.

Running on ArchLinux with `rustup` installed and `rustup default stable` set.

```
❯ cargo --version
cargo 1.79.0 (ffa9cf99a 2024-06-03)
❯ rustc --version
rustc 1.79.0 (129f3b996 2024-06-10)
❯ uname -a    
Linux archlinux-laptop 6.6.38-1-lts #1 SMP PREEMPT_DYNAMIC Tue, 09 Jul 2024 11:08:50 +0000 x86_64 GNU/Linux
```

**Comment by juliuszint** [comment]
Hi, thanks for the issue. The problem should be fixed now.

**Comment by leonkacowicz** [comment]
It worked here! I was having a problem with it not finding the device, but then I figured I had to run this with sudo and then it worked perfecly.
