### ISSUE TITLE
This is not an issue.

### ISSUE THREAD

**Issue by 925-Studio** [juliuszint/asdbctl#7]
First of all, thank you so much for this tool. The story goes like this, I've recently started to get into the habit of disconnecting the power after shutting down to give all my devices a better rest. However, this morning when I turned on my computer again, I noticed that my monitor brightness was restored to its highest level. I almost went downstairs to get my Mac Mini. but I'm lazy so I googled it and then your tool came up first. As one with programming experience, your tool makes more sense to set up and use. So purposely sending this message to say thanks!

**Comment by juliuszint** [comment]
You are very welcome and thank you for this kind note.
