### ISSUE TITLE
Status of upstreaming hid_bl driver?

### ISSUE THREAD

**Issue by maghoff** [juliuszint/asdbctl#8]
Hi! Thanks for all your work in this! I just installed the hidraw branch today, along with the [gnome-shell extension](https://github.com/flightmansam/gnome-asdbctl-slider) and it works like a charm :heart: 

But before that, I went on a quest to figure out how far along this functionality is on its way to… I guess, just working out of the box with my distro. It seems like you are the same one that's writing a kernel module for this, is that right? I'm not initiated into kernel development, so I can only find bits and pieces of the discussions along the way. It seemed that this work was progressing nicely around September 2023, and that's the last I have been able to find. Is this still on its way to mainline Linux? Any news on this?

Thanks,
– Magnus

**Comment by juliuszint** [comment]
Hi Magnus, yes, I have also made a kernel driver so that it would work out of the box. I did a few iterations but even with these improvements, this driver will not go upstream, because userspace seems to only be able to handle a single backlight under `/sys/class/backlight/*`. If there are more, each with a different minimum, maximum and step size, strange things happen.

I know what would need to change, but I have not been able to figure it out in my spare time. The way forward would be to create a new API using DRM connectors and properties on them. But for this I need to know, what DRM connector maps to which HID device.

Recently I have seen things working (somewhat) out of the box with KDE, it shows up in the brightness and color applet but the maximum brightness is wrong. Probably not useful for you because you are using Gnome anyways.

**Comment by maghoff** [comment]
Thanks for the update. I'm very happy to be using asdbctl in the meantime, but I take it that you are still going for getting it upstreamed eventually. Cool! Always happy to see the fundamental solution winning out in the end :smile:

Best of luck going forward!

**Comment by juliuszint** [comment]
Sure! Yes, I would still very much like to get it working in the kernel. But its a long way. Even if the new API is there,  then work needs to be done in KDE and Gnome to get it to users. Thanks for the kind words.

**Comment by flightmansam** [comment]
> Hi! Thanks for all your work in this! I just installed the hidraw branch today, along with the [gnome-shell extension](https://github.com/flightmansam/gnome-asdbctl-slider) and it works like a charm ❤️

@maghoff have made some updates to the slider!

**Comment by ecrsail** [comment]
So I have found a hardware platform that the asdbctl utility does not work
"out of the box" on, but the problem as far as I can tell is not specific
to asdbctl but rather some incompatibility with how USB4 over TB is being
detected and supported.

The platform in question is the LattePanda Sigma -- an i5 based SBC with
dual native Thunderbolt 4 support.

https://www.lattepanda.com/lattepanda-sigma

Ubuntu 24.04 finds the Apple Studio Display but does not seem to detect or
map the USB functionality contained therein.   I have connected the ASD to
a traditional Intel desktop system and Ubuntu finds not just the ASD
display device but also the audio and camera devices as well any USB-C
peripherals attached to the ASD.   But on the LattePanda, only the video
device is found and enumerated at boot.

I am a bit of a loss as to how to debug this.   boltctl shows the same
output on both platforms, but on the LattePanda, but none of the expected
USB hardware shows up on lshw, lsusb, or aplay -l

For fun, I tried installing the latest asdbctl using the hidapi interface
and not too surprisingly there was no asdbl- device installed after reboot.

So this likely means there is something unique about how Thunderbolt
support has been supported on the LattePanda Sigma hardware that is
preventing the USB peripherals from being found by the Ubuntu kernel.   I
have not been able to figure out what this might be so I could explore
possible solutions.

If you have read this far and have any ideas, I would be grateful for any
suggestions.

--Eric

**Comment by juliuszint** [comment]
This sounds like a tough one. My advice would be to first try a very recent kernel (not sure what the Ubuntu that you are using offers). If you see the same issues with 6.12, then maybe a kernel mailing list is your best friend. The CPU seems to support Thunderbolt 4 so I don`t see a good reason why only the DP alt mode is working and not any other USB devices.

**Comment by ecrsail** [comment]
I truly appreciate this feedback.   Thank you.

Eric
