### ISSUE TITLE
Does this work over a dispayport to usb-c cable or does it need a thunderbolt cable?

### ISSUE THREAD

**Issue by ch0c0l8ra1n** [juliuszint/asdbctl#9]
^title

**Comment by juliuszint** [comment]
This will most likely not work. The HID device is a USB device and if your cable only supports DP via USB-Cs alt mode, then there will be no HID USB device to control the brightness with.

**Comment by ch0c0l8ra1n** [comment]
@juliuszint  Just wondering what cable do you use?

**Comment by juliuszint** [comment]
I am using the thunderbolt 4 cable that shipped with the display.

**Comment by flightmansam** [comment]
There are two options if you want to connect just a DisplayPort and USB. If your PC has free PCIE slots you can buy a Delock 90161 (or similar) displayport to USB-C ALT card. Then you can plug in and control the display (and enjoy seamless USB hub, camera and audio) with any normal USB-C cable. Alternatively you can use an external tool like a Rextron VCPUC-60 to do the very same. If you want links to these let me know and I'll go dig them up. I have had success with both options. You can get the old version of the Delock on Aliexpress for very cheap (the new one has faster USB-C).

**Comment by alexellis** [comment]
This needs to be a pinned issue. I'd think a few notes in the README on cables and connectivity options would help a lot of people landing here.

@flightmansam is it possible to use a Display Port to USB-C cable / adapter to plug into an Nvidia card on the PC? The 3060 I have supports DP 1.4.

Once that's in place, is there any way to adjust the brightness, without having to bypass the Nvidia card for graphics, and having to install a PCIe card?

Edit: does the Rextron VCPUC-60 allow for me to plug in a display port cable into the back of the discrete GPU and also have the USB HID detected for brightness control?

**Comment by flightmansam** [comment]
> @flightmansam is it possible to use a Display Port to USB-C cable / adapter to plug into an Nvidia card on the PC? The 3060 I have supports DP 1.4.

This will only do video and not brightness/audio/camera/hub but so long as the DP to USB-C cable supports bidirectional (most do) you should be in buisness. 

> Edit: does the Rextron VCPUC-60 allow for me to plug in a display port cable into the back of the discrete GPU and also have the USB HID detected for brightness control?

Yep! I'll send pics of my setup tomorrow if you like? (I'm currently out of town).

**Comment by ch0c0l8ra1n** [comment]
@flightmansam The display port to usb c cable I got was sold as bi-directional but I can't access the cameras or set the brightness through my pc. I'd love to see a pic of your setup.

**Comment by juliuszint** [comment]
@alexellis I would be happy to accept MR for a README update. I have always been using the TB4 cable that came with the display, meaning I do not have anything to share for other cables.

**Comment by flightmansam** [comment]
@ch0c0l8ra1n I forgot to do this! Tonight (maybe)

**Comment by guilhermetk** [comment]
While this isn’t exactly the scenario described by @ch0c0l8ra1n, I’m using a Studio Display with a Dell Optiplex 3000 Micro and this cable ([Amazon link](https://www.amazon.com/dp/B0BNX7MS6N?ref_=ppx_hzsearch_conn_dt_b_fed_asin_title_9&th=1)). I’m able to control the brightness using asdbctl, and both audio and the webcam are working as well.

**Comment by richardstrnad** [comment]
My Setup:
- AMD 9950X
- MSI MAG X670E Tomahawk
- Linux (Arch)

What didn't work:
- USB-C from the Mainboard to the Apple Studio Display
  - I had display output until the bootloader, but the screen went black after that.
- Display Port from the Mainboard to Delock 90161, USB-C from Delock 90161 to the Apple Studio Display
  - Same behavior as with a direct USB-C cable, black after bootloader.

What works:
- Display Port from the Mainboard to the Apple Studio Display with a DP1.4 to USB-C Cable
  - But this is only Video, so I can't use this util and not the speakers/cam/mic.
- [This Cable](https://www.amazon.com/dp/B0BNX7MS6N) works without an issue and also with 5K for me
  - Can now change brightness & use the Speakers (didn't try mic & cam, but should work as well)

Maybe this helps someone in the future, I spent quite some time to get this working :)

@juliuszint Thanks for the tool 🥳

**Comment by flightmansam** [comment]
> What didn't work:
>... 
> * Display Port from the Mainboard to Delock 90161, USB-C from Delock 90161 to the Apple Studio Display
>   
>   * Same behavior as with a direct USB-C cable, black after bootloader.

I experienced an issue similar to this when using the Delock and a nvidia card (with nvidia Linux driver). I was able to ssh into my system and using a gnome display cli tool ([gnome-monitor-config](https://github.com/jadahl/gnome-monitor-config)) I saw that for some reason the display's default resolution is an impossible 2560x2560 and the next resolution available (19:10 5K) wasn't selected. As soon as I used the CLI tool to select the proper resolution I got picture back. I guess the bootloader pre-selects 1080 or maybe even 480 as a compatibility thing?

Hope this helps!!

**Comment by flightmansam** [comment]
> * [This Cable](https://www.amazon.com/dp/B0BNX7MS6N) works without an issue and also with 5K for me

This is an amazing find and definitely the cheapest possible solution to this problem! I'm going to order one!

**Comment by guilhermetk** [comment]
@flightmansam Thank you so much for pointing me to gnome-monitor-config! I’ve been struggling with the black screen issue on GNOME for quite some time and only managed to get it working with KDE, but that’s not my preferred DE. Now I have my gnome working flawlessly!

**Comment by flightmansam** [comment]
[this cable](https://www.aliexpress.com/item/1005006673239763.html?spm=a2g0o.productlist.main.29.2a33PC2JPC2Jew&algo_pvid=95ebcea4-d141-416f-8fd4-f38f7bab6352&algo_exp_id=95ebcea4-d141-416f-8fd4-f38f7bab6352-28&pdp_ext_f=%7B%22order%22%3A%22122%22%2C%22eval%22%3A%221%22%7D&pdp_npi=4%40dis%21AUD%2136.39%2136.39%21%21%21165.86%21165.86%21%40210318e817469367314592144e774f%2112000037980812962%21sea%21AU%212654342030%21X&curPageLogUid=25K6wNSuex5i&utparam-url=scene%3Asearch%7Cquery_from%3A) works too if you don't want to support amazon!

**Comment by ecrsail** [comment]
Yes, cables from this vendor have been demonstrated to work:WJESOG HDMI to USB C Adapter... https://www.amazon.com/dp/B0BNX61QNVI’ve used it with an HDMI/USB to Thunderbolt cable.  There have been reports of it working just fine with the similar DisplayPort cable.  As an aside, just because you have a pure Thunderbolt interface does not imply the software will always see the onboard USB-C hardware.  I have found two SBCs where this is the case.On May 10, 2025, at 21:16, Samuel Hutchinson ***@***.***> wrote:﻿
flightmansam left a comment (juliuszint/asdbctl#9)
this cable works too if you don't want to support amazon!
